# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2024-09-06 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 15, 55, 32, 551294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 15, 55, 32, 551294, tzinfo=utc)),
        ),
    ]
